name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

# See https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# env:
#   Platform: x64 # For Msbuild
#   Configuration: Release # For Msbuild

jobs:
  ci:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            ice_build_flags: srcs
          - os: macos-14
            ice_build_flags: srcs
          - os: windows-2022
            ice_build_flags: /t:BuildDist

    runs-on: ${{ matrix.os }}
    steps:
      - name: Windows Environment
        if: runner.os == 'Windows'
        run: |
          echo "Platform=x64" >> $env:GITHUB_ENV
          echo "Configuration=Release" >> $env:GITHUB_ENV
          echo "IceHome=${{ github.workspace }}\ice" >> $env:GITHUB_ENV

          # We need to replace \ with / in the path, specifically for Gradle
          $iceHome = "${{ github.workspace }}/ice"
          $iceHome = $iceHome.Replace("\", "/")
          echo "ICE_HOME=$iceHome" >> $env:GITHUB_ENV

      - name: Linux/MacOS Environment
        if: runner.os != 'Windows'
        run: |
          echo "ICE_HOME=${{ github.workspace }}/ice" >> $GITHUB_ENV
          echo "IceHome=${{ github.workspace }}/ice" >> $GITHUB_ENV

      - name: Checkout Ice
        uses: actions/checkout@v4
        with:
          repository: zeroc-ice/ice
          ref: main
          path: ice

      - name: Setup Ice Build Dependencies
        uses: ./ice/.github/actions/setup-dependencies

      - name: Build Ice on ${{ matrix.os }}
        uses: ./ice/.github/actions/build
        timeout-minutes: 60
        with:
          working_directory: ice
          build_flags: ${{ runner.os == 'Windows' && '/t:BuildDist' || 'srcs' }}

      - name: Publish C++ NuGet Packages on ${{ matrix.os }}
        timeout-minutes: 5
        working-directory: ice/cpp/msbuild
        run: msbuild ice.proj /t:Publish
        if: runner.os == 'Windows'

      - name: Publish C# NuGet Packages on ${{ matrix.os }}
        timeout-minutes: 5
        working-directory: ice/csharp/msbuild
        run: dotnet msbuild ice.proj /t:Publish

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ice-demos

      - name: Build C++ Demos on ${{ matrix.os }}
        uses: ./ice/.github/actions/build
        timeout-minutes: 20
        with:
          working_directory: ice-demos/cpp
          msbuild_project: msbuild/ice.proj

      - name: Generate C++ Build Systems on ${{ matrix.os }}
        timeout-minutes: 5
        working-directory: ice-demos/cpp
        run: find . -name CMakeLists.txt -execdir cmake -B build -S . \;

      - name: Build C++ Demos on ${{ matrix.os }}
        timeout-minutes: 20
        working-directory: ice-demos/cpp
        run: find . -name CMakeLists.txt -type d -execdir cmake --build build -- \;

      - name: Build C# Demos on ${{ matrix.os }}
        timeout-minutes: 20
        working-directory: ice-demos/csharp
        run: dotnet build

      - name: Run .NET format
        run: dotnet format --verify-no-changes "./ice-demos/csharp/C# NET demos.sln"
        if: runner.os == 'Linux'

      - name: Build Java Demos on ${{ matrix.os }}
        timeout-minutes: 20
        working-directory: ice-demos/java
        env:
          # For Ice Builder for Gradle
          CPP_PLATFORM: x64
          CPP_CONFIGURATION: Release
        run: ./gradlew build

      - name: Build JavaScript Demos on ${{ matrix.os }}
        timeout-minutes: 20
        working-directory: ice-demos/js
        env:
          # For Ice Builder for Gulp
          CPP_PLATFORM: x64
          CPP_CONFIGURATION: Release
        run: |
          npm install
          npx gulp build

      - name: Build Swift Demos on ${{ matrix.os }}
        timeout-minutes: 20
        working-directory: ice-demos/swift
        run: find . -name Package.swift -execdir swift build \;
        if: runner.os == 'macOS'
