name: Build and test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

# See https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Ice
        uses: actions/checkout@v4
        with:
          repository: zeroc-ice/ice
          ref: main
          path: ice

      - name: Setup Ice Build Dependencies
        uses: ./ice/.github/actions/setup-dependencies

      - name: Build Iice on ${{ matrix.os }}
        uses: ./ice/.github/actions/build
        timeout-minutes: 90
        with:
          working_directory: ice/cpp

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ice-demos

      - name: Build Ice Demos on ${{ matrix.os }}
        timeout-minutes: 90
        working-directory: ice-demos/cpp
        run: |
          export ICE_HOME=$GITHUB_WORKSPACE/ice
          make
